# Generated by Django 5.2.5 on 2025-08-07 06:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, unique=True, verbose_name='Fakultet nomi')),
                ('qisqartma', models.CharField(blank=True, max_length=20, verbose_name='Qisqartma')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kurs raqami')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['raqam'],
            },
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Viloyat nomi')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.CharField(max_length=10, verbose_name='Xona raqami')),
                ('qavat', models.IntegerField(verbose_name='Qavat')),
                ('sig_imi', models.IntegerField(choices=[(2, '2 kishilik'), (3, '3 kishilik'), (4, '4 kishilik')], verbose_name="Sig'imi")),
                ('band_orinlar', models.IntegerField(default=0, verbose_name="Band o'rinlar")),
                ('konditsioner', models.BooleanField(default=False, verbose_name='Konditsioner')),
                ('muzlatgich', models.BooleanField(default=False, verbose_name='Muzlatgich')),
                ('narxi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Oylik to'lov")),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['bino', 'qavat', 'raqam'],
            },
        ),
        migrations.CreateModel(
            name='YotoqxonaBino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.IntegerField(unique=True, verbose_name='Bino raqami')),
                ('nomi', models.CharField(max_length=100, verbose_name='Bino nomi')),
                ('turi', models.CharField(choices=[('erkak', '🚹 Erkaklar binosi'), ('ayol', '🚺 Ayollar binosi')], max_length=10, verbose_name='Bino turi')),
                ('manzil', models.TextField(verbose_name='Manzil')),
                ('qavatlar_soni', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Qavatlar soni')),
                ('har_qavatda_xonalar', models.IntegerField(verbose_name='Har qavatdagi xonalar soni')),
                ('wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('oshxona', models.BooleanField(default=True, verbose_name='Oshxona')),
                ('kir_yuvish', models.BooleanField(default=True, verbose_name='Kir yuvish xonasi')),
                ('issiq_suv', models.BooleanField(default=True, verbose_name='Issiq suv')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yotoqxona binosi',
                'verbose_name_plural': 'Yotoqxona binolari',
                'ordering': ['raqam'],
            },
        ),
        migrations.CreateModel(
            name='YotoqxonaAriza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariza_raqami', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ariza raqami')),
                ('fish', models.CharField(max_length=300, verbose_name="To'liq ism familiya")),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('tugilgan_sana', models.DateField(verbose_name="Tug'ilgan sana")),
                ('pasport', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{7}$', 'Format: AA1234567')], verbose_name='Pasport seriya raqami')),
                ('telefon', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Format: +998901234567')], verbose_name='Telefon raqami')),
                ('telefon_qoshimcha', models.CharField(blank=True, max_length=13, verbose_name="Qo'shimcha telefon (ota-ona)")),
                ('tuman', models.CharField(max_length=100, verbose_name='Tuman/Shahar')),
                ('manzil', models.TextField(verbose_name="To'liq manzil")),
                ('oila_azolari', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name="Oila a'zolari soni")),
                ('imtiyoz_turi', models.CharField(choices=[('yoq', "Imtiyoz yo'q"), ('1_guruh_nogironlik', '1-guruh nogironlik'), ('2_guruh_nogironlik', '2-guruh nogironlik'), ('3_guruh_nogironlik', '3-guruh nogironlik'), ('yetim', 'Yetim'), ('bir_ota_ona', 'Bir ota-ona tarbiyasida'), ('kam_taminlangan', "Kam ta'minlangan oila"), ('kop_bolali', "Ko'p bolali oila (4+ farzand)"), ('temir_daftar', 'Temir daftar'), ('ayollar_daftari', 'Ayollar daftari'), ('yoshlar_daftari', 'Yoshlar daftari')], default='yoq', max_length=30, verbose_name='Imtiyoz turi')),
                ('imtiyoz_hujjat', models.FileField(blank=True, null=True, upload_to='imtiyoz/%Y/%m/', verbose_name='Imtiyoz hujjati (PDF/rasm)')),
                ('xona_turi_afzallik', models.IntegerField(choices=[(2, '2 kishilik'), (3, '3 kishilik'), (4, '4 kishilik')], default=4, verbose_name='Afzal xona turi')),
                ('ariza_sanasi', models.DateTimeField(auto_now_add=True, verbose_name='Ariza sanasi')),
                ('oquv_yili', models.CharField(max_length=9, verbose_name="O'quv yili")),
                ('holat', models.CharField(choices=[('yangi', '📝 Yangi'), ('korilmoqda', "👀 Ko'rib chiqilmoqda"), ('imtixon', '📋 Imtixon kutilmoqda'), ('tasdiqlandi', '✅ Tasdiqlandi'), ('rad_etildi', '❌ Rad etildi'), ('bekor', '🚫 Bekor qilindi')], default='yangi', max_length=20, verbose_name='Holat')),
                ('tasdiqlangan_sana', models.DateTimeField(blank=True, null=True)),
                ('rad_sababi', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('izoh', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arizalar', to='dormitory_app.fakultet', verbose_name='Fakultet')),
                ('kurs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dormitory_app.kurs', verbose_name='Kurs')),
                ('tayinlangan_xona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dormitory_app.xona', verbose_name='Tayinlangan xona')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory_app.viloyat', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Yotoqxona arizasi',
                'verbose_name_plural': 'Yotoqxona arizalari',
                'ordering': ['-ariza_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='ArizaIzohi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(verbose_name='Izoh matni')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('ariza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='dormitory_app.yotoqxonaariza')),
            ],
            options={
                'verbose_name': 'Ariza izohi',
                'verbose_name_plural': 'Ariza izohlari',
                'ordering': ['-sana'],
            },
        ),
        migrations.AddField(
            model_name='xona',
            name='bino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xonalar', to='dormitory_app.yotoqxonabino'),
        ),
        migrations.AddIndex(
            model_name='yotoqxonaariza',
            index=models.Index(fields=['holat', 'ariza_sanasi'], name='dormitory_a_holat_0057bc_idx'),
        ),
        migrations.AddIndex(
            model_name='yotoqxonaariza',
            index=models.Index(fields=['fakultet', 'kurs'], name='dormitory_a_fakulte_6e9b24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xona',
            unique_together={('bino', 'raqam')},
        ),
    ]
