# Generated by Django 5.2.5 on 2025-08-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xona',
            name='sig_imi',
            field=models.IntegerField(choices=[(2, '2 kishilik'), (3, '3 kishilik'), (4, '4 kishilik'), (5, '5 kishilik'), (6, '6 kishilik')], verbose_name="Sig'imi"),
        ),
        migrations.AlterField(
            model_name='yotoqxonaariza',
            name='xona_turi_afzallik',
            field=models.IntegerField(blank=True, choices=[(2, '2 kishilik'), (3, '3 kishilik'), (4, '4 kishilik'), (5, '5 kishilik'), (6, '6 kishilik')], null=True, verbose_name='Afzal xona turi'),
        ),
    ]
